Fix validate_package_maintainers to handle absent category hints.
When an old source-only package (which has a .hint containing just skip:) is
changed to an installable package, a category doesn't exist for all
versions.

Traceback (most recent call last):
  File "./calm/calm.py", line 508, in do_daemon
    state.packages = process_uploads(args, state)
  File "./calm/calm.py", line 192, in process_uploads
    if not package.validate_packages(args, merged_packages[arch]):
  File "./calm/package.py", line 680, in validate_packages
    validate_package_maintainers(args, packages)
  File "./calm/package.py", line 703, in validate_package_maintainers
    if any(['_obsolete' in packages[p].version_hints[vr]['category'] for vr
in packages[p].version_hints]):
  File "./calm/package.py", line 703, in <listcomp>
    if any(['_obsolete' in packages[p].version_hints[vr]['category'] for vr
in packages[p].version_hints]):
KeyError: 'category'